version: '3'

services:
  # Database for Airflow
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Airflow Scheduler
  airflow-scheduler:
    build: ./airflow   # build custom image from Dockerfile in ./airflow
    command: scheduler
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres

  # Airflow Webserver
  airflow-webserver:
    build: ./airflow   # build custom image from Dockerfile in ./airflow
    command: webserver
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - airflow-scheduler

  # dbt service
  dbt:
    build: ./dbt   # build custom image from Dockerfile in ./dbt
    volumes:
      - ./dbt:/usr/app/dbt
    working_dir: /usr/app/dbt
    command: ["dbt", "run"]
    depends_on:
      - postgres

volumes:
  postgres_data: